### ISSUE TITLE
Large .exr image is just black

### ISSUE THREAD

**Issue by roflmaostc** [Tom94/tev#238] opened 2024-10-01 11:17 UTC
Hi,

I'm using 
```
tev — The EXR Viewer
version 1.27dev (64 bit)
```
on 
```
Linux nearth 6.10.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000 x86_64 GNU/Linux
```

If I try to display this [image](https://wolke.sumpi.org/index.php/s/5BQyWFEw8E2A74C), it shows as black.

However, if I make the size smaller (cropping it), it works.
No errors in the terminal.
Attached a screenshot.

[
![Screenshot_2024-10-01_13-13-34](https://github.com/user-attachments/assets/2f59b2a4-0752-4486-9cea-b62312209bde)
](url)

Thanks a lot,

Felix

CC: @bathal1

**Comment by Tom94** [comment] 2024-10-01 13:15
Hi, thanks for reporting this!

At first I suspected a texture size limitation in the graphics engine, but after a bit of troubleshooting I found a few places in the codebase that overflowed then the pixel count reached into (or close to) billions. I patched them up just now and it seems to work on my Windows and macOS systems -- but I won't have access to a Linux machine until tomorrow.

Could you try cloning the latest commit on `master`, re-compiling, and loading the image again? If confirmed working on your end, I'll push a hotfix release.

![image](https://github.com/user-attachments/assets/42a92a76-5af5-4104-9969-997d193e3462)

**Comment by roflmaostc** [comment] 2024-10-01 13:28
Hm, now it crashes with some other error messages when loading the image:

```
╰─λ build/tev /home/fxw/Nextcloud/mitsuba/final.exr                                                                                                         0 (10.612s) < 15:26:06
15:26:13 SUCCESS  Initialized IPC, listening on 127.0.0.1:14158
15:26:13 INFO     Launching with 8 bits of color and LDR display support.
15:26:13 SUCCESS  Loaded /home/fxw/Nextcloud/mitsuba/final.exr via OpenEXR after 0.797 seconds.
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  2
  Serial number of failed request:  368
  Current serial number in output stream:  371
```

I had like ~28GB of memory still available on my laptop.

**Comment by Tom94** [comment] 2024-10-01 13:37
The memory bottleneck you're likely running into is your GPU's VRAM rather than your CPU's RAM. If you can figure out which GPU model you have, you can look up the amount of VRAM it has. If that's below 4GB, it's likely the cause of your issue.

On my machine, my GPU uses 1.6 GB idle and 4.5 GB while having the image loaded.

**Comment by roflmaostc** [comment] 2024-10-03 11:37
On my big Linux desktop it works.

I'm not sure why my laptop fails, it should be solid and has 32GB RAM.
Maybe it's an Arch Linux thing?

**Comment by Tom94** [comment] 2024-10-03 12:34
Thanks for reporting back -- I also tested on my own Linux system in the meanwhile. Seems to work, so I'll close this issue!

As for the 32GB of RAM that you mention: this number likely refers to your system (CPU) RAM and not your GPU's available video RAM (VRAM). I say this, because there isn't really any laptop GPU with that much VRAM (integrated or dedicated) on the market today (except for high-end macbooks, but you wouldn't run Arch on those). I recommend checking your system specs in more detail to find out which GPU you have and how much VRAM it has.

**Closed by Tom94** 2024-10-03 12:34 UTC
