### ISSUE TITLE
'Deep' Image

### ISSUE THREAD

**Issue by Chadt54** [Tom94/tev#121] opened 2021-04-06 21:17 UTC
This image makes Tev go crazy to 100% CPU.

[deep.0001.zip](https://github.com/Tom94/tev/files/6267607/deep.0001.zip)

**Comment by Tom94** [comment] 2021-06-28 05:40
Loads fine on my machine. Which version of tev and which operating system are you using?

**Comment by Tom94** [comment] 2021-07-29 05:28
Closing due to inability to reproduce

**Closed by Tom94** 2021-07-29 05:28 UTC
